// Generated by CoffeeScript 1.12.5
(function() {
  var Building, Mine, Radar,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Building = (function(superClass) {
    extend(Building, superClass);

    function Building(x, y) {
      this.x = x;
      this.y = y;
      this.sprite = sprites.building;
      Building.__super__.constructor.apply(this, arguments);
      this.offsetY = -this.h;
      this.canBeDestroyed = false;
      this.hitbox = buildHitbox(this.offsetX, this.offsetY, 1, 3, 13, 32);
    }

    return Building;

  })(Enemy);

  Mine = (function(superClass) {
    extend(Mine, superClass);

    function Mine(x, y) {
      this.x = x;
      this.y = y;
      this.sprite = sprites.mine;
      Mine.__super__.constructor.apply(this, arguments);
      this.points = 100;
      this.hitbox = buildHitbox(this.offsetX, this.offsetY, 1, 1, 15, 15);
    }

    Mine.prototype.onExplode = function() {
      var direction, i, len, ref, results, shotSpeed;
      shotSpeed = 50 * Screen.pixelD;
      ref = [0, Math.PI, -Math.PI / 2, Math.PI / 2];
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        direction = ref[i];
        results.push(Game.world.getNextEnemyShot().fire(this.x, this.y, shotSpeed, direction));
      }
      return results;
    };

    return Mine;

  })(Enemy);

  Radar = (function(superClass) {
    extend(Radar, superClass);

    function Radar(x, y) {
      this.x = x;
      this.y = y;
      this.sprite = sprites.radar;
      Radar.__super__.constructor.apply(this, arguments);
      this.offsetY = -this.h;
      this.cooldown = Math.random() * 5;
      this.firePattern = [3, 0.5];
      this.patternIndex = 0;
      this.points = 100;
      this.hitbox = buildHitbox(this.offsetX, this.offsetY, 1, 2, 15, 16);
    }

    Radar.prototype.update = function(delta) {
      this.cooldown -= delta;
      if (this.cooldown < 0) {
        if (!this.offScreen) {
          this.fire();
        }
        this.patternIndex += 1;
        if (this.patternIndex === this.firePattern.length) {
          this.patternIndex = 0;
        }
        return this.cooldown = this.firePattern[this.patternIndex];
      }
    };

    Radar.prototype.fire = function() {
      var direction, i, len, ref, results, shotSpeed;
      shotSpeed = 50 * Screen.pixelD;
      ref = [Math.PI, -Math.PI / 2, 0];
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        direction = ref[i];
        results.push(Game.world.getNextEnemyShot().fire(this.x - 3 * Screen.pixelW, this.y - 13 * Screen.pixelH, shotSpeed, direction));
      }
      return results;
    };

    return Radar;

  })(Enemy);

  window.Building = Building;

  window.Mine = Mine;

  window.Radar = Radar;

}).call(this);

//# sourceMappingURL=building.js.map
