// Generated by CoffeeScript 1.12.5
(function() {
  var PlayerShot, Ship;

  Ship = (function() {
    function Ship() {
      this.sprite = sprites.ship;
      this.w = this.sprite.imageW;
      this.h = this.sprite.imageH;
      this.offsetX = this.w / -2;
      this.offsetY = this.h / -2;
      this.x = 100;
      this.y = 100;
      this.facingLeft = false;
      this.vSpeed = 100 * Screen.pixelH;
      this.hSpeed = 150 * Screen.pixelW;
      this.minY = 18 * Screen.pixelH;
      this.maxY = 168 * Screen.pixelH;
      this.offScreen = false;
      this.cooldown = 0.3;
      this.hitbox = buildHitbox(this.offsetX, this.offsetY, 0, 0, 32, 13);
    }

    Ship.prototype.update = function(delta) {
      if (this.cooldown > 0) {
        this.cooldown -= delta;
        if (this.cooldown < 0) {
          return this.cooldown = 0;
        }
      }
    };

    Ship.prototype.draw = function(cameraOffsetX) {
      return this.sprite.draw(this.x + this.offsetX - cameraOffsetX, this.y + this.offsetY, this.facingLeft);
    };

    Ship.prototype.moveV = function(delta, direction) {
      this.y += direction * delta * this.vSpeed;
      if (this.y < this.minY) {
        this.y = this.minY;
      }
      if (this.y > this.maxY) {
        return this.y = this.maxY;
      }
    };

    Ship.prototype.moveH = function(delta, direction) {
      this.x += direction * delta * this.hSpeed;
      return this.facingLeft = direction < 0;
    };

    Ship.prototype.fireShot = function() {
      var shotOffset, shotSpeed;
      if (this.cooldown > 0) {
        return;
      }
      shotSpeed = 200 * Screen.pixelW;
      shotOffset = 14 * Screen.pixelW;
      if (this.facingLeft) {
        shotSpeed *= -1;
        shotOffset *= -1;
      }
      Game.world.getNextPlayerShot().fire(this.x + shotOffset, this.y + 2 * Screen.pixelH, shotSpeed);
      return this.cooldown = 0.1;
    };

    return Ship;

  })();

  PlayerShot = (function() {
    function PlayerShot() {
      this.sprite = sprites.playerShot;
      this.w = this.sprite.imageW;
      this.h = this.sprite.imageH;
      this.offsetX = this.w / -2;
      this.offsetY = this.h / -2;
      this.dead = true;
      this.hitbox = buildHitbox(this.offsetX, this.offsetY, 0, 1, 16, 4);
    }

    PlayerShot.prototype.fire = function(x, y, hSpeed) {
      this.x = x;
      this.y = y;
      this.hSpeed = hSpeed;
      this.dead = false;
      this.offScreen = false;
      return this.facingLeft = this.hSpeed < 0;
    };

    PlayerShot.prototype.draw = function(cameraOffsetX) {
      return this.sprite.draw(this.x + this.offsetX - cameraOffsetX, this.y + this.offsetY, this.facingLeft);
    };

    PlayerShot.prototype.update = function(delta) {
      this.x += this.hSpeed * delta;
      if (this.offScreen) {
        return this.dead = true;
      }
    };

    return PlayerShot;

  })();

  window.Ship = Ship;

  window.PlayerShot = PlayerShot;

}).call(this);

//# sourceMappingURL=ship.js.map
