// Generated by CoffeeScript 1.12.5
(function() {
  var building, convert, guppie, mine, radar, ship, shot, ufo;

  guppie = '...##\n##..##\nx#..##\n##.####\n.#.#--#\n.###----\n.###----\n.#.#--#\n##.####\nx#..##\n##..##\n...##';

  mine = '...#\n...#\n....-\n....-\n...#\n...#\n.-.xx#.#\n.-.xx#.#\n#.#xx.-\n#.#xx.-\n....#\n....#\n...-\n...-\n....#\n....#';

  building = '...-\n...-\n...-\n..---\n.-.#.-\n.-.#.-\n.-.#.-\n.-###-\n.-.#.-\n.-.#.-\n.-.#.-\n.-###-\n.-.#.-\n.-.#.-\n.-.#.-\n-#####-\n-.#.#.-\n-.#.#.-\n-.#.#.-\n-#####-\n-.#.#.-\n-.#.#.-\n-.#.#.-\n-#####-\n-.#.#.-\n-.#.#.-\n-.#.#.-\n-#####-\n-.....-\n-.xxx.-\n-.x.x.-\n-------';

  ship = '####\n###\n.###\n..###\n.#####\n.------xxx\n#-------xxx\n#--------xxx-#\n#------------##\n#-###---------##\n.###---------##\n###\n####';

  radar = '...xx\n...xx\n...xx\n...xx\n--------\n.------\n..----\n...##\n...##\n.######\n.-####-\n.-....-\n.-....-\n-.-..-.-\n-.-..-.-\n---..---';

  ufo = '...--\n..#--#\n.------\n-..--xx-\n-..--xx-\n-..--xx-\n-..--xx-\n.------\n..-##-';

  shot = '.....x#\n-..---x#\n..-.--x#\n.....x#';

  convert = function(spriteChars, width) {
    var binString, char, dec, hex, i, j, len, len1, line, lines, text;
    lines = spriteChars.split("\n");
    text = '';
    for (i = 0, len = lines.length; i < len; i++) {
      line = lines[i];
      line = (line + '...................').slice(0, width);
      binString = '';
      for (j = 0, len1 = line.length; j < len1; j++) {
        char = line[j];
        binString += char === '.' ? '00' : char === '#' ? '11' : char === '-' ? '10' : char === 'x' ? '01' : 'xx';
      }
      dec = parseInt(binString, 2);
      hex = ('000000' + dec.toString(16)).slice(-4);
      text += hex + "\n";
    }
    return console.log(text);
  };

  convert(shot, 8);

}).call(this);

//# sourceMappingURL=sprites.js.map
